Repository Consensys/scribble, pull requests merged in 2020-12, with the labels that each got.

#3 Add badges
  .drone.yml
  README.md
  package-lock.json
  package.json
Labels: documentation

#4 Support adding units
  package-lock.json
  src/spec-lang/ast/number.ts
  src/spec-lang/expr_grammar.pegjs
  test/unit/parser.spec.ts
Labels: enhancement

#5 Disallow if_succeeds annotation for contract definitions
  src/bin/scribble.ts
  src/instrumenter/annotations.ts
  test/integration/scribble/run/invalid.spec.ts
  test/multifile_samples/inheritance1/C.sol
  test/multifile_samples/inheritance1/flat.sol.expected
  test/multifile_samples/inheritance1/propertyMap.json.expected
  test/samples/if_succeeds_on_contract.invalid.sol
  test/samples/if_succeeds_on_free_function.invalid.sol
  test/samples/invariant_on_function.invalid.sol
Labels: bug
